"use client"
import { Inter,Outfit } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Toaster } from "sonner";
import "./globals.css";
const inter = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignOutUrl="/courses" >
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>   
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
